language: python
sudo: false

deploy:
  provider: pypi
  user: chriswbartley
  password:
    secure: Q8CbIBRGhNMOK79g+hBCxS+CBPaGjZLfwr7gbG1YunHvmhIlUEKruKIEI9E3AB3+bUjRV6SmgxHBNgMaV4IohGGmxZK78wlpGzslrgwKae7X1Yw06wC6sAQuGNHheiOlVnZn8kp5q7Ej6ljpdT1xvmJEZIN67xF1fj2Zv0J2KMew2YPvFcOgkaCkA5jgrpyIC8atdVNL8jzY+DHDJvY4HkJELRJ3NKqpk2hvrrhUReQJfBkMolebpX9wZHrGGJcF5rJr0Am0wYyJa0+0vbZ8tgDp5qyLnr3hl3EC9VV7h52zttrN01svj/RSOc5+y04Cqi/RJm6YZ5YN1fjOyp0Pm9oHw1ATH3Q63hoMTKspyXCAD2Z3AF+x3KUh5x8ePFm3seVxZg6KmE3pMGZ7PavAz1L2vuLeeeAop3Y3XybSGIYmPul3n76k5fyyVOdDtlrDe6IL/nkT/3xnc64waiIsvL8Z6EWeOrH00b8c5/4L+dqwfDNgZDOLGBKj5Rdccu03Qt0VFP3ollX5KjzOm0fj/DAyG50TI2NkNbfZSfLeC8nhibGjW3k9tMn2d6ZqeNFOfxcBsJ/uVzkG2VNNtRzxS7GcLu3t4ZFYFjCMXIegTJOUcqsQhM7tpYREOV4wkuiFjCIf1toxgW7+8U1Ps+XKSHHQQgX+XSWJkDf3UaU5tVM=
  on:
    tags: true
    repo: chriswbartley/monoboost

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '3.6'


install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- mkdir for_test
- cd for_test
- py.test --pyargs monoboost --cov-report term-missing --cov=monoboost

after_success:
- coveralls
- cd..
